### ISSUE TITLE
Confusing dir structure and files

### ISSUE THREAD

**Issue by vbanos** [Eagle19243/SPN2_with_Google_Sheet_Web#11]
Why having 3 dirs `home`, `spn2_google_sheet_web`, `src`? It doesn't make sense and its confusing to someone who tries to understand your code. Please put everything in one folder.

Why do you need `db.sqlite3`? Do you keep something in the database?

**Comment by Eagle19243** [comment]
Have you worked on Django project before?

**Comment by vbanos** [comment]
Yes.

**Comment by Eagle19243** [comment]
This project is based on Django. Then what is your expectation in dir structure and files?

**Comment by vbanos** [comment]
No problem, I can explain:
* Isn't it possible to put all the files from `home` and `SPN2_with_Google_Sheet_Web` in one folder? `home` is not a good name, to deploy this in production, we'll need a name like `spn2_google_sheet_web`.
* `src` should be deleted I guess, its empty.

**Comment by eagle19243** [comment]
Regarding to directory structure, I would love to follow the dir structure described in 
https://django-project-skeleton.readthedocs.io/en/latest/structure.html
Are you ok with this?

**Comment by Eagle19243** [comment]
Exactly `Stand-alone website`...

**Comment by vbanos** [comment]
Thats fine!

**Comment by eagle19243** [comment]
@vbanos, do you have any Django project that I can reference? And if `home` is not a good name, what is your expectation?

**Comment by vbanos** [comment]
No, I'm sorry, I don't have any Django project handy.

The reason for selecting a proper folder name is that when we install your package in production, we'll copy the `home` dir in the virtual environment along with other packages and nobody will know what `home` means. If the folder name is `spn2_google_sheets` it will be obvious. I suggest to pick a folder name like that.

**Comment by eagle19243** [comment]
Ok, I got it

**Comment by vbanos** [comment]
The file organization is so much better in the new version. Thank you!
